import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

import { I18nProvider } from "@/context/i18n-context";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			className={cn(
				"font-sans antialiased",
				geistSans.variable,
				geistMono.variable,
				inter.variable
			)}
			lang="en"
		>
			<body>
				<I18nProvider>
					<Navbar />
					{children}
					<Footer />
				</I18nProvider>
			</body>
		</html>
	);
}
